### ISSUE TITLE
Visibility / Wind speed unit

### ISSUE THREAD

**Issue by bluefoxlee** [tsunglung/TwANWS#1]
Visibility 

| 內容  | 建議修改 |
| ------------- | ------------- |
| km | m |
| 顯示選項 | 能見度 |
| km/h | kts |
| 大氣壓單位 | mb |

Metar 以 9999 表示 10 公里和以上 電碼文字 CAVOK

![RCBS_visibility](https://user-images.githubusercontent.com/894044/117916939-b8730780-b31a-11eb-987c-a79d6ebe12fc.png)

**Comment by tsunglung** [comment]
我有把能見度的值跟單位, 切開. 再傳給 HA 去顯示. 但是 visibility_unit 好像沒有作用, 
如果不把值跟單位, 切開, 實用性會降低一點.

"顯示選項" 的翻譯是 HA 那邊翻的 (visibility)

**Comment by bluefoxlee** [comment]
有的，有看到。確實切開來**非常**實用

visibility 這個我找一下翻譯 看能不能改 因為有可能是與其他項目共用 尷尬

**Comment by bluefoxlee** [comment]
自己 Bug report 給自己？！ 哈
能見度翻譯已修正  XD

**Comment by tsunglung** [comment]
weather 的部份，找不到地方改單位
sensor 的部份，可以改單位。但是為了一致，偶還是同樣的單位

**Comment by bluefoxlee** [comment]
了解。內碼限制那就沒辦法了。先關 issue. 
謝謝

**Comment by bluefoxlee** [comment]
能見度 翻譯 2021.6.b0 終於更新修正

**Comment by tsunglung** [comment]
> 能見度 翻譯 2021.6.b0 終於更新修正

感謝您的無私供獻
