### ISSUE TITLE
Wind Speed Error

### ISSUE THREAD

**Issue by bluefoxlee** [tsunglung/TwANWS#2]
感覺這個整合應該只有我在使用 回報問題有點抱歉 XD

目前 Wind speed 在顯示資料上 應該有點擷取資料誤判

![HA](https://user-images.githubusercontent.com/894044/155278709-a4498d97-f82b-4788-9350-cac2a4e85a58.png)
Home Assistant 內顯示為 1527 Knot

![RCBS](https://user-images.githubusercontent.com/894044/155278724-30f057d3-e6d6-441a-b0e3-5e1c2bf94485.png)
METAR 顯示資料應該為 15 Knot 陣風 27 Knot。G 代表 Gust。如果沒有陣風回報 顯示則為正常

**Comment by niceboygithub** [comment]
I still feel happy even only one using this integration.

I will fix after checked.

**Comment by tsunglung** [comment]
I still feel happy even only one using this integration.

I will fix it after checked.

**Comment by bluefoxlee** [comment]
> I still feel happy even only one using this integration.
> I will fix it after checked.

The integration helps me a lot with automation notification. actually I believe its very help if people lives near airport and know to how use it. Aviation weather tends to be more accurate IMHO.

So Thanks again for the help.

**Comment by bluefoxlee** [comment]
It seems the issue is still there with new update.

**Comment by niceboygithub** [comment]
I am not sure what is the exact content.
I guess wrong.
Not 15G27KT.

**Comment by tsunglung** [comment]
I am not sure what is the exact content.
I guess wrong.
Not 15G27KT.

**Comment by bluefoxlee** [comment]
You probably already know. 
Most of time wind info in METAR (RAW data) shows like:
01009KT = Dirction 010, Speed 09 Knot

When gust wind, it shows:
05014G24KT = Direction 050, Speed 14 Knot Gust 24 Knot.

Err and sometimes:
VRB01KT = Variable, Wind direction changes. 01 Knot. :)

Not sure if line 121 [0] after G cause the issue? since I have no idea about programming.

**Comment by tsunglung** [comment]
![C3FBE390-600F-4103-B996-3B1FFD703B04](https://user-images.githubusercontent.com/46878487/155906949-8af1e518-6d9a-4287-8b04-9a7eaa1d60ba.jpeg)
What this one display while gust wind.

**Comment by bluefoxlee** [comment]
> What this one display while gust wind.

There is no gust wind in this case. Check the raw data below shows:
34004KT = Direction 340 and 04 Knot.

**Comment by tsunglung** [comment]
No, I means when it is gust wind, what it display for gust wind

**Comment by bluefoxlee** [comment]
> No, I means when it is gust wind, what it display for gust wind

I guess it will shows "X 哩/時，陣風 X 哩/時", will try to capture screenshot when I see it (when gust).

**Comment by tsunglung** [comment]
Thanks, I need them in English and Chinese

**Comment by tsunglung** [comment]
By the way, HA weather looks can not display extra gust wind in wind speed

**Comment by bluefoxlee** [comment]
Actually just wind speed is good enough IMHO. I use visibility and wind as notification to see if airport is closing.
(although technically you will need to calculate crosswind).

Check [NWS](https://www.home-assistant.io/integrations/nws/) integration. it separate 'wind gust' as another sensor.

**Comment by bluefoxlee** [comment]
Here you go.
![RCKW](https://user-images.githubusercontent.com/894044/155960177-8fd5bec0-f256-4d97-a623-bcd26d3fdde7.png)

Again, just wind speed is good enough if that's too troublesome. ^^

**Comment by bluefoxlee** [comment]
The new update cause new error last below. Testes with two installed HA. 

Unexpected error fetching ANWS AOAWS for "Station Name" data: name 'LENGTH_KILOMETERS' is not defined

**Comment by bluefoxlee** [comment]
> Unexpected error fetching ANWS AOAWS for "Station Name" data: name 'LENGTH_KILOMETERS' is not defined

New updated fixed not defined issue, unfortunately gust wind is still there. 
As I suggest, perhaps it's easier to just leave it without gust wind. so you don't spent to much time on this minor issue.

**Comment by tsunglung** [comment]
The raw data is "8&nbsp;浬/時&nbsp;陣風&nbsp;18&nbsp;浬/時"

There is no whitespace in it. I have the wrong guess. Let me fix it again.

**Comment by bluefoxlee** [comment]
> There is no whitespace in it. I have the wrong guess. Let me fix it again.

Got it. Updated and will report back once I got result. 
Thanks again. XD

**Comment by bluefoxlee** [comment]
Kind of lucky (bad luck?) those days. Was unable to test due to stable weather. 
Will report back once it shows. 

Update: I actually find another visibility distance issue. but I think I will get more data before I try to report it.

**Comment by bluefoxlee** [comment]
Got gust wind 1-2 days ago and report looks ok.
Issue closed.
